backend:
  replicaCount: 2
  image:
    repository: green-banking-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  mongoUri: "your-mongo-uri"
  service:
    port: 5000
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"

frontend:
  replicaCount: 2
  image:
    repository: green-banking-frontend
    tag: "latest"
    pullPolicy: IfNotPresent
  backendUrl: "http://backend-service:5000"
  service:
    port: 3000
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"
