apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "green-banking.frontend.fullname" . } }
  labels: { { - include "green-banking.frontend.labels" . | nindent 4 } }
spec:
  replicas: { { .Values.frontend.replicaCount } }
  selector:
    matchLabels:
      { { - include "green-banking.frontend.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "green-banking.frontend.labels" . | nindent 8 } }
      annotations: { { - toYaml .Values.frontend.podAnnotations | nindent 8 } }
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: { { .Values.frontend.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.frontend.service.port } }
              name: http
          env:
            - name: REACT_APP_BACKEND_URL
              value: { { .Values.frontend.backendUrl } }
          resources: { { - toYaml .Values.frontend.resources | nindent 12 } }
