apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  MONGO_URI: mongodb+srv://finnbar:wUk54NprYsw4caJe@cluster0.ywien.mongodb.net/greenbanking?retryWrites=true&w=majority&appName=Cluster0
